import{a as h,S as w,i as y}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function l(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(t){if(t.ep)return;t.ep=!0;const n=l(t);fetch(t.href,n)}})();h.defaults.baseURL="https://pixabay.com/api/";const E="42494540-1ca0643de0a334de28e64a581";class L{constructor(e){this.page=1,this.query=null,this.perPage=e||15,this.lastPage=null}async fetchPhotosByQuery(){const e=await h.get("",{params:{image_type:"photo",orientation:"horizontal",q:this.query,page:this.page,per_page:this.perPage,key:E,safesearch:!0}});return e.status===200?(this.page++,console.log("API Response:",e.data),e.data):(console.error("Error fetching photos:",e.statusText),null)}resetPage(){this.page=1}}function B(s){return s.hits.map(e=>`<li class="image-search">
        <a class="gallery-link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <ul class="gallery-image-info">
          <li class="image-items">
            <p class="image-info"><span class="text">Likes</span>${e.likes}</p>
            <p class="image-info"><span class="text">Views</span>${e.views}</p>
            <p class="image-info"><span class="text">Comments</span>${e.comments}</p>
            <p class="image-info"><span class="text">Downloads</span>${e.downloads}</p>
          </li>
        </ul>
      </li>`).join("")}const r=new L,u=document.getElementById("gallery-container"),o=document.getElementById("load-more-btn"),p=document.getElementById("loading-indicator"),m=document.getElementById("search-form"),I=document.getElementById("search-input"),i=document.getElementById("end-of-results-message"),x=new w(".gallery a",{nav:!0,captions:!0,captionsData:"alt",captionDelay:150});i.textContent="We're sorry, but you've reached the end of search results.";i.style.display="none";o.style.display="none";let f=0;function P(){const s=f*2;window.scrollBy({top:s,behavior:"smooth"}),console.log(P)}function d(){o.style.display="none",i.style.display="none"}async function v(s){s.preventDefault();const e=m.elements.search.value;if(u.innerHTML="",p.style.display="block",r.resetPage(),o.style.display="none",i.style.display="none",r.query=I.value.trim(),e===""){y.error({title:"Error",message:"Please enter a search query."});return}async function l(){try{const a=await b();a&&a.hits.length===0&&y.error({timeout:1e3,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}catch(a){console.error("Error during initial search:",a)}}l(),o.style.display="block"}function g(){o.style.display="none"}async function b(){try{const s=await r.fetchPhotosByQuery();if(s&&s.hits.length>0){const e=u.firstElementChild;e&&(f=e.getBoundingClientRect().height),u.innerHTML+=B(s),x.refresh(),P(),s.totalHits<=r.page*r.perPage&&(d(),g())}else d(),g()}finally{p.style.display="none"}}m.addEventListener("submit",v);o.addEventListener("click",async()=>{p.style.display="block",await b()});
//# sourceMappingURL=commonHelpers.js.map
